name: First WorkFlow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Wello World!"
      - name: Print Good Bye
        run: echo "Done BYE!"
